site_name: Unofficial hub module documentation

nav:
    - Getting started: 'index.md'
    - Hub: 'hub.md'
    - Led: 'led.md'
    - Sound: 'sound.md'
    - Image: 'image.md'
    - Display: 'display.md'
    - Button: 'button.md'
    - Motion: 'motion.md'
    - Port : 'port.md'
    - Sensors (Device): 'sensors.md'
    - Motor: 'motors.md'  
    - Virtual Com Port: 'VCP.md'  
    - Battery: 'battery.md'
    - Data types and constants: 'data_types.md'

#   - Bluetooth: 'bluetooth.md'
#   - Config: 'config.md'
#   - supervision: 'supervision.md'
theme:
    name: readthedocs
    custom_dir: 'overrides/'
extra_css: ['custom.css']
copyright: Â© Copyright 2021 Nard Strijbosch
site_author: Nard Strijbosch
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - attr_list



